apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cryptnono.fullname" . }}
  labels:
    {{- include "cryptnono.labels" . | nindent 4 }}
data:
  execsniper.json: {{ .Values.detectors.execsniper.config | toJson | quote }}
