apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bloodcoins.fullname" . }}
  labels:
    {{- include "bloodcoins.labels" . | nindent 4 }}
data:
  detector.bt: |
    {{ .Files.Get "files/detector.bt" | nindent 4 }}
