apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bloodcoins.fullname" . }}
  labels:
    {{- include "bloodcoins.labels" . | nindent 4 }}
data:
  monero.bt: |
    {{ .Files.Get "files/monero.bt" | nindent 4 }}
