# Chart.yaml v2 reference: https://helm.sh/docs/topics/charts/#the-chartyaml-file
#
apiVersion: v2
name: cryptnono
version: "0.0.1-set.by.chartpress"
description: Kill processes attempting to mine Monero on your k8s cluster.
type: application
