image:
  repository: quay.io/yuvipanda/cryptnono
  tag: set-by-chartpress
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

containerSecurityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



nodeSelector: {}

tolerations:
  # We want to run *everywhere* by default, regardless of any taints
  - operator: "Exists"
    effect: "NoSchedule"

affinity: {}

fetchKernelHeaders:
  resources: {}
  image:
    # Custom image
    # Brings in https://github.com/iovisor/kubectl-trace/pull/184 and
    # https://github.com/iovisor/kubectl-trace/pull/185 so it works on non COS hosts
    name: yuvipanda/kubectl-trace-init
    tag: 9af18f1197b1b377be4816c2761049745b64c6b8

# Enable and configure various killers we have
detectors:
  execwhacker:
    debug: true
    enabled: true
    resources: {}
    configs: {}
  monero:
    enabled: true
    resources: {}
