image:
  repository: quay.io/iovisor/bpftrace
  # tag is set to something recent from:
  # - https://github.com/iovisor/bpftrace/releases
  # - https://quay.io/repository/iovisor/bpftrace?tab=tags
  tag: v0.17.0-vanilla_llvm12_clang_glibc2.31
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

containerSecurityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations:
      # common tolerations for
      - key: "hub.jupyter.org/dedicated"
        operator: "Equal"
        value: "user"
        effect: "NoSchedule"
      - key: "hub.jupyter.org_dedicated"
        operator: "Equal"
        value: "user"
        effect: "NoSchedule"
      - key: "k8s.dask.org/dedicated"
        operator: "Equal"
        value: "worker"
        effect: "NoSchedule"
      - key: "k8s.dask.org_dedicated"
        operator: "Equal"
        value: "worker"
        effect: "NoSchedule"

affinity: {}
