image:
  repository: quay.io/yuvipanda/cryptnono
  tag: 0.0.1-0.dev.git.27.h01b4f25
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

containerSecurityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



nodeSelector: {}

tolerations:
      # common tolerations for
  - key: "hub.jupyter.org/dedicated"
    operator: "Equal"
    value: "user"
    effect: "NoSchedule"
  - key: "hub.jupyter.org_dedicated"
    operator: "Equal"
    value: "user"
    effect: "NoSchedule"
  - key: "k8s.dask.org/dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"
  - key: "k8s.dask.org_dedicated"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"

affinity: {}

fetchKernelHeaders:
  resources: {}
  image:
    # Custom image
    # Brings in https://github.com/iovisor/kubectl-trace/pull/184 and
    # https://github.com/iovisor/kubectl-trace/pull/185 so it works on non COS hosts
    name: yuvipanda/kubectl-trace-init
    tag: 9af18f1197b1b377be4816c2761049745b64c6b8

# Enable and configure various killers we have
detectors:
  execsniper:
    enabled: true
    resources: {}
    configs: {}
  monero:
    enabled: true
    resources: {}
